-- Keep the local restore schema aligned with Production.
-- Face embeddings contain 192 floating-point values generated by the app.
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS face_embedding vector(192);
