package handler

import (
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/Nattamon123/employee/backend/internal/domain"
	"github.com/Nattamon123/employee/backend/internal/middleware"
	"github.com/Nattamon123/employee/backend/internal/repository"
	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

type TaskEventHandler struct {
	repo *repository.TaskEventRepo
}

func NewTaskEventHandler(repo *repository.TaskEventRepo) *TaskEventHandler {
	return &TaskEventHandler{repo: repo}
}

func contextUserID(c *gin.Context) *uuid.UUID {
	raw, ok := c.Get(middleware.ContextKeyUserID)
	if !ok {
		return nil
	}
	userID, ok := raw.(uuid.UUID)
	if !ok || userID == uuid.Nil {
		return nil
	}
	return &userID
}

func eventContentPointer(value string) *string {
	return &value
}

// recordTaskEvent is the only writer used by task mutation handlers. Actor IDs
// always come from authenticated server context, never from a client payload.
func recordTaskEvent(
	c *gin.Context,
	repo *repository.TaskEventRepo,
	scope *repository.TaskEventScope,
	action string,
	content string,
	forcedTaskID *uuid.UUID,
) error {
	if repo == nil {
		return fmt.Errorf("task event repository is not configured")
	}

	var uID uuid.UUID
	if ptr := contextUserID(c); ptr != nil {
		uID = *ptr
	}

	event := &domain.TaskEvent{
		ID:        uuid.New(),
		UserID:    uID,
		EventType: "system",
		Action:    action,
		Content:   eventContentPointer(content),
		CreatedAt: time.Now(),
	}
	if scope != nil {
		event.TaskID = scope.TaskID
		event.ListID = scope.ListID
		event.CardID = scope.CardID
		event.SubItemID = scope.SubItemID
	}
	if forcedTaskID != nil {
		event.TaskID = *forcedTaskID
	}

	return repo.Create(c.Request.Context(), event)
}

// ListByTask GET /api/tasks/:id/events?list_id=&card_id=
func (h *TaskEventHandler) ListByTask(c *gin.Context) {
	taskID, err := uuid.Parse(c.Param("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid task id"})
		return
	}

	var listID *uuid.UUID
	if value := c.Query("list_id"); value != "" {
		parsed, parseErr := uuid.Parse(value)
		if parseErr != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid list id"})
			return
		}
		listID = &parsed
	}

	var cardID *uuid.UUID
	if value := c.Query("card_id"); value != "" {
		parsed, parseErr := uuid.Parse(value)
		if parseErr != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid card id"})
			return
		}
		cardID = &parsed
	}

	taskOnly := c.Query("task_only") == "true"

	events, err := h.repo.ListByTask(c.Request.Context(), taskID, listID, cardID, taskOnly)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to load task activity"})
		return
	}
	c.JSON(http.StatusOK, gin.H{"ok": true, "data": events})
}

// AddComment POST /api/tasks/:id/events
// This endpoint deliberately creates comments only. System/audit events are
// generated by backend mutation handlers and cannot be forged by the client.
func (h *TaskEventHandler) AddComment(c *gin.Context) {
	taskID, err := uuid.Parse(c.Param("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid task id"})
		return
	}

	var req struct {
		Content string `json:"content"`
		ListID  string `json:"list_id"`
	}
	if err := c.ShouldBindJSON(&req); err != nil || strings.TrimSpace(req.Content) == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "comment is required"})
		return
	}

	var listID *uuid.UUID
	if value := strings.TrimSpace(req.ListID); value != "" {
		parsed, parseErr := uuid.Parse(value)
		if parseErr != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid list id"})
			return
		}
		scope, scopeErr := h.repo.ScopeForList(c.Request.Context(), parsed)
		if errors.Is(scopeErr, sql.ErrNoRows) {
			c.JSON(http.StatusNotFound, gin.H{"error": "list not found"})
			return
		}
		if scopeErr != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to validate list"})
			return
		}
		if scope == nil || scope.TaskID != taskID {
			c.JSON(http.StatusBadRequest, gin.H{"error": "list does not belong to task"})
			return
		}
		listID = &parsed
	}

	var uID uuid.UUID
	if ptr := contextUserID(c); ptr != nil {
		uID = *ptr
	}

	event := &domain.TaskEvent{
		ID:        uuid.New(),
		TaskID:    taskID,
		ListID:    listID,
		UserID:    uID,
		EventType: "comment",
		Action:    "comment_added",
		Content:   eventContentPointer(strings.TrimSpace(req.Content)),
		CreatedAt: time.Now(),
	}
	if err := h.repo.Create(c.Request.Context(), event); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to save comment"})
		return
	}

	created, err := h.repo.ListByTask(c.Request.Context(), taskID, listID, nil, false)
	if err == nil {
		for _, item := range created {
			if item.ID == event.ID {
				c.JSON(http.StatusCreated, gin.H{"ok": true, "data": item})
				return
			}
		}
	}
	c.JSON(http.StatusCreated, gin.H{"ok": true, "data": event})
}

// ListAll GET /admin/tasks/events
func (h *TaskEventHandler) ListAll(c *gin.Context) {
	events, err := h.repo.ListAll(c.Request.Context())
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to load activity log"})
		return
	}
	c.JSON(http.StatusOK, gin.H{"ok": true, "data": events})
}
